--drop table AIR_LOADER_LOG;

create table  AIR_LOADER_LOG
(LOAD_ID integer generated by default as identity (start with 1), 
LAST_RUN varchar(255),
THIS_RUN varchar(255),
STATUS varchar(255), 
SERVER_COUNT integer,
SERVER_COMPLETE integer,
SERVER_FAILED integer,
JOB_COUNT integer,
JOB_COMPLETE integer,
JOB_FAILED integer,
AUDIT_COUNT integer,
AUDIT_COMPLETE integer,
AUDIT_FAILED integer,
primary key (LOAD_ID));
