--insert into AIR_LOADER_LOG(LAST_RUN,STATUS, SERVER_COUNT,SERVER_COMPLETE,SERVER_FAILED,JOB_COUNT,JOB_COMPLETE,JOB_FAILED,AUDIT_COUNT,AUDIT_COMPLETE,AUDIT_FAILED) values ('Feb 18 23:38','Load Job Data Complete','868','859','9','868','859','9','868','859','9'); 
truncate table AIR_LOADER_LOG;
commit;